### ISSUE TITLE
UserWarning: Module deepnox was already imported from

### ISSUE THREAD

**Issue by fmichaud** [deepnox-io/python-wipbox#10]
```shell
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from deepnox.third import pydantic
/home/fmichaud/.local/lib/python3.9/site-packages/deepnox/__init__.py:11: UserWarning: Module deepnox was already imported from /home/fmichaud/.local/lib/python3.9/site-packages/deepnox/__init__.py, but /home/fmichaud/Documents/Workspace/oss/wipbox is being added to sys.path
```

**Comment by fmichaud** [comment]
@NicoLaDta : please could you analyze this issue ?

**Comment by NicoLaDta** [comment]
T'import pydantic depuis un folder a toi ?

**Comment by NicoLaDta** [comment]
Ok, so, the first thing I see is that you are giving the values ​​of libraries to variables but you are not currently returning anything

**Comment by NicoLaDta** [comment]
We need to try something like that
** 
return _DEFAULT_POOL.request(
        method,
        url,
        body=body,
        fields=fields,
        headers=headers,
        preload_content=preload_content,
        decode_content=decode_content,
        redirect=redirect,
        retries=retries,
        timeout=timeout,
        json=json,
    )
**

Not exactly the same but I think it's a starting point

**Comment by NicoLaDta** [comment]
https://stackoverflow.com/questions/13915269/why-do-i-get-userwarning-module-dap-was-already-imported-from-none

**Comment by fmichaud** [comment]
It was due to a bad configuration into setup.py
